### ISSUE TITLE
Install rosette.application error

### ISSUE THREAD

**Issue by nujcharee** [rosette-api-community/rosette-for-excel#2]
Hi there
Before we installed rosette.application do I need to change anything in the file? Currently it tries to look or localhost and I got error below
PLATFORM VERSION INFO
    Windows             : 6.1.7601.65536 (Win32NT)
    Common Language Runtime     : 4.0.30319.42000
    System.Deployment.dll       : 4.6.1055.0 built by: NETFXREL2
    clr.dll             : 4.6.1076.0 built by: NETFXREL3STAGE
    dfdll.dll           : 4.6.1055.0 built by: NETFXREL2
    dfshim.dll          : 4.0.41209.0 (Main.041209-0000)

SOURCES
    Deployment url          : file:///C:/viz/rosette-for-excel-master/rosette.application
    Deployment Provider url     : http://localhost/rosette4excel/rosette.application

ERROR SUMMARY
    Below is a summary of the errors, details of these errors are listed later in the log.
    \* Activation of C:\viz\rosette-for-excel-master\rosette.application resulted in exception. Following failure messages were detected:
        + Downloading http://localhost/rosette4excel/rosette.application did not succeed.
        + Unable to connect to the remote server
        + No connection could be made because the target machine actively refused it 127.0.0.1:80

COMPONENT STORE TRANSACTION FAILURE SUMMARY
    No transaction error was detected.

WARNINGS
    There were no warnings during this operation.

OPERATION PROGRESS STATUS
    \* [14/10/2016 13:44:43] : Activation of C:\viz\rosette-for-excel-master\rosette.application has started.

ERROR DETAILS
    Following errors were detected during this operation.
    \* [14/10/2016 13:44:45] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
        - Downloading http://localhost/rosette4excel/rosette.application did not succeed.
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
            at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
            at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
            at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
            at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
            at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
            at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
        --- Inner Exception ---
        System.Net.WebException
        - Unable to connect to the remote server
        - Source: System
        - Stack trace:
            at System.Net.HttpWebRequest.GetResponse()
            at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
        --- Inner Exception ---
        System.Net.Sockets.SocketException
        - No connection could be made because the target machine actively refused it 127.0.0.1:80
        - Source: System
        - Stack trace:
            at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
            at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

COMPONENT STORE TRANSACTION DETAILS
    No transaction information is available.

**Comment by cp2boston** [comment]
I'm assuming you git cloned the repo.  From File Explorer, double click on rosette.application and it will install the file.  You do need the 1.0.0.2 directory to be available.  I've tested this on Windows 7 and up.  Which version of Office are you using?  Do you have something blocking your localhost?

**Comment by nujcharee** [comment]
Yes I did cloned it from github.  Its a work computer so maybe blocked by group policy. Do I need IIS installed to communicate to localhost? Sorry I am not a infrastructure type of person just a data gal. Thanks

**Comment by cp2boston** [comment]
There is no IIS requirement.  

Just to make sure the current installer is working, I just tested it on a Windows VM with nothing special added to it other than Office.  The current installer is good for Office 2010 and 2013.  We will be releasing one that supports 2016 fairly soon.

We use Addin-Express to manage the different Office versions and the installer is built using their deployment tools.  If you look in the manifest, you'll see that it uses localhost.  I apologize for not knowing more about the IT side of things.

**Comment by nujcharee** [comment]
not at all - i will try it from a personal PC to see if there's any different. I am on wins 7 too with office 2013. The thing is personal PC is wins10 so its not like for like comparison.

**Comment by cp2boston** [comment]
You are the first person outside of our company to try the plugin, so any feedback you provide is extremely valuable.  I had hoped to avoid an MSI, but your experience may force me to revisit it.

**Comment by nujcharee** [comment]
hi
looks ike if i cloned this to desktop and installed it installed successfully :)

**Comment by cp2boston** [comment]
That's great news.  I'm still going to investigate a better installer.
